language: python

python:
  - 3.7
  - 3.9
install:
  - pip install -U pip
  - pip install poetry
  - poetry install --no-root --remove-untracked
script:
  - pytest
  - coverage run tests/*
  - coverage report --fail-under=60
