name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Load cached venv
        id: load-cached-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.load-cached-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Run Tests
        run: poetry run pytest
